site_name: ${{ values.name }}
site_description: Documentation for ${{ values.name }}

nav:
  - Home: index.md
  - Development: development.md
  - Deployment: deployment.md
  - API Reference: api.md

plugins:
  - techdocs-core
