apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: keycloak-configs

# MANUAL STEPS:
#   BEFORE sync: oc apply -k cluster-configs/keycloak/secrets/
#   AFTER sync:  oc apply -f cluster-configs/keycloak/rhdh-realm-import.yaml
#                (realm CRD only exists after operator installs)

resources:
  - keycloak-operator.yaml
  - keycloak-instance.yaml

commonLabels:
  config.openshift.io/component: keycloak
  config.openshift.io/managed-by: gitops
